### ISSUE TITLE
Failure to fetch from http://archive.ubuntu.com

### ISSUE THREAD

**Issue by shartse** [delphix/appliance-build#146] opened 2018-11-05 18:04 UTC
We have seen two successive failures of this type (both trying to fetch `iw_4.14-0.1_amd64.deb`)
```
08:57:08 E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/i/iw/iw_4.14-0.1_amd64.deb  Undetermined Error [IP: 91.189.88.149 80]
08:57:08 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/169/execution/node/95/log/
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/170/

**Comment by shartse** [comment] 2018-11-05 19:15
Hit this for the third time in a row: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/171/

**Comment by prakashsurya** [comment] 2018-11-05 19:18
FWIW, I'm able to download the file on my laptop:
```
$ wget http://archive.ubuntu.com/ubuntu/pool/main/i/iw/iw_4.14-0.1_amd64.deb
--2018-11-05 11:17:28--  http://archive.ubuntu.com/ubuntu/pool/main/i/iw/iw_4.14-0.1_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 91.189.91.23, 91.189.88.161, 91.189.88.162, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|91.189.91.23|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 75396 (74K) [application/x-debian-package]
Saving to: ‘iw_4.14-0.1_amd64.deb’

iw_4.14-0.1_amd64.deb              100%[================================================================>]  73.63K   355KB/s    in 0.2s    

2018-11-05 11:17:29 (355 KB/s) - ‘iw_4.14-0.1_amd64.deb’ saved [75396/75396]
```

**Comment by pzakha** [comment] 2019-03-05 15:09
Hit again: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/2034/console

**Comment by jwk404** [comment] 2019-03-28 15:30
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/743/

**Comment by sravyamks** [comment] 2019-04-02 17:27
Hit on - http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/pre-push/928/console
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/pre-push/926/console

**Comment by ahrens** [comment] 2019-04-11 19:54
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/827/

internal-dev-gcp failed with :
```00:03:32         "\u001b[91mE: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gcc-7/libstdc++-7-dev_7.3.0-27ubuntu1~18.04_amd64.deb  Undetermined Error [IP: 91.189.88.152 80]",```

**Comment by shartse** [comment] 2019-04-17 17:08
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/nightly/82/console

Failed in branch external-demo-esx:
`Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/parted/parted_3.2-20ubuntu0.2_amd64.deb  Undetermined Error [IP: 91.189.91.23 80]`

**Comment by jwk404** [comment] 2019-06-20 22:47
Hit again, but this time on what I assume is our internal mirror.

http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/10082/consoleFull

```
00:10:09.834  Fetched 403 MB in 6s (72.8 MB/s)
00:10:09.834  E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/i/intel-microcode/intel-microcode_3.20190618.0ubuntu0.18.04.1_amd64.deb  404  Not Found [IP: 54.191.70.203 80]
00:10:09.834  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by prakashsurya** [comment] 2019-06-20 23:10
`http://us-west-2.ec2.archive.ubuntu.com` .. this is still an Ubuntu managed server.. I don't think we have our internal mirror yet.

**Comment by pzakha** [comment] 2019-08-06 20:51
Similar issue, related to external repositories:
```
16:27:21  Err:17 http://ddebs.ubuntu.com bionic-proposed/main amd64 Packages
16:27:21    File has unexpected size (53200 != 49624). Mirror sync in progress? [IP: 91.189.94.8 80]
16:27:21    Hashes of expected file:
16:27:21     - Filesize:49624 [weak]
16:27:21     - SHA512:07d99fd8c1d2ea64657518fbf60b6fb6b8b9b777a079f2f0ac58c6c90e3e25da25f677b385e43388baceee3c0100e99e8a8d24d5e1ac8707c31048694221ed1e
16:27:21     - SHA256:0e3b7676fa984bd49d5971e5a72d44f5ed892651757151aee67625f2c7d99a12
16:27:21     - SHA1:d83aee8eb351d245b78b7fa5081ec26e4c14d300 [weak]
16:27:21     - MD5Sum:985529c8a1558e8f2b198eaacb19f777 [weak]
16:27:21    Release file created at: Tue, 06 Aug 2019 12:53:51 +0000
```

**Comment by jwk404** [comment] 2019-09-10 15:05
08:31:37          "\u001b[91mE: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/universe/binary-amd64/Packages.gz  File has unexpected size (1283704 != 1283717). Mirror sync in progress? [IP: 91.189.88.176 80]", 
08:31:37          "   Hashes of expected file:", 
08:31:37          "    - Filesize:1283717 [weak]", 
08:31:37          "    - SHA256:b8f21390285ded6ceb63f1f4dcb54fd3f0070149c34908b2bde9549ef55ebe45", 
08:31:37          "    - SHA1:c38241560772c5bcba0517bcedace86d5abde139 [weak]", 
08:31:37          "    - MD5Sum:a9dc2b6c4222cf5b047265d32051c095 [weak]", 
08:31:37          "   Release file created at: Tue, 10 Sep 2019 13:55:43 +0000", 
08:31:37          "E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-amd64/Packages.gz  ", 
08:31:37          "E: Some index files failed to download. They have been ignored, or old ones used instead.",

**Comment by jwk404** [comment] 2019-09-10 18:42
Similar failure: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/1761/console

but this time from security.ubuntu.com

```11:07:48          "\u001b[91mE: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/systemd/libsystemd0_237-3ubuntu10.29_amd64.deb  404  Not Found [IP: 91.189.88.173 80]", 
11:07:48          "E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/systemd/libudev1_237-3ubuntu10.29_amd64.deb  404  Not Found [IP: 91.189.88.173 80]", 
11:07:48          "E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/systemd/systemd_237-3ubuntu10.29_amd64.deb  404  Not Found [IP: 91.189.88.173 80]", 
11:07:48          "E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/systemd/systemd-sysv_237-3ubuntu10.29_amd64.deb  404  Not Found [IP: 91.189.88.173 80]", 
11:07:48          "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?", 
11:07:48          "\u001b[0mFetched 184 MB in 4min 32s (676 kB/s)"
```

**Comment by pzakha** [comment] 2019-09-10 19:12
As a side note, the failure here is while updating the docker container. This failure will not go away once we switch appliance-build to use our third-party mirror as the docker container will keep having the default `/etc/apt/sources.list` files. We would need to also update that file to use the mirror to fix this issue.

**Comment by pzakha** [comment] 2019-09-10 20:52
Looking more at this latest failure, it seems like Ubuntu has many internal mirrors for `security.ubuntu.com`, probably for load balancing:
```
$ nslookup security.ubuntu.com
Server:		172.16.105.2
Address:	172.16.105.2#53

Non-authoritative answer:
Name:	security.ubuntu.com
Address: 91.189.88.24
Name:	security.ubuntu.com
Address: 91.189.88.176
Name:	security.ubuntu.com
Address: 91.189.91.26
Name:	security.ubuntu.com
Address: 91.189.88.177
Name:	security.ubuntu.com
Address: 91.189.88.149
Name:	security.ubuntu.com
Address: 91.189.88.174
Name:	security.ubuntu.com
Address: 91.189.91.23
Name:	security.ubuntu.com
Address: 91.189.88.173
Name:	security.ubuntu.com
Address: 91.189.91.24
Name:	security.ubuntu.com
Address: 91.189.88.31
Name:	security.ubuntu.com
Address: 91.189.91.14
Name:	security.ubuntu.com
Address: 91.189.88.175
Name:	security.ubuntu.com
Address: 91.189.88.162
```
Some of them are fine while others seem to be missing some of the packages, which is why we are running into such a mess. If you run `wget http://security.ubuntu.com/ubuntu/pool/main/s/systemd/systemd-sysv_237-3ubuntu10.29_amd64.deb` manually, it will sometimes work and sometimes not, depending on which IP it chooses to download from.

**Comment by shartse** [comment] 2019-09-30 20:54
8 out of 9 variant builds hit this keyserver issue agagin: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/19279/console

Error reading https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&exact=on&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367: Service Unavailable

**Comment by shartse** [comment] 2019-10-01 19:39
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/19474/console
```
 "E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/multiverse/binary-amd64/Packages.gz  ", 
08:09:43          "E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-amd64/Packages.gz  ", 
08:09:43          "E: Some index files failed to download. They have been ignored, or old ones used instead.", 
```

**Comment by prashks** [comment] 2019-10-22 21:20
Similar issue running into error 503 Service Unavailable - http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/22251/console


```12:20:46      "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'python3-docker' 'qemu' 'zfsutils-linux'' failed: E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/fontconfig_2.12.6-0ubuntu2_amd64.deb  503  Service Unavailable [IP: 34.212.136.213 80]\nE: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/libi/libiscsi/libiscsi7_1.17.0-1.1_amd64.deb  503  Service Unavailable [IP: 34.212.136.213 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", 
12:20:46      "rc": 100, 
12:20:46      "stderr": "E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/fontconfig_2.12.6-0ubuntu2_amd64.deb  503  Service Unavailable [IP: 34.212.136.213 80]\nE: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/libi/libiscsi/libiscsi7_1.17.0-1.1_amd64.deb  503  Service Unavailable [IP: 34.212.136.213 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", 
12:20:46      "stderr_lines": [
12:20:46          "E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/fontconfig_2.12.6-0ubuntu2_amd64.deb  503  Service Unavailable [IP: 34.212.136.213 80]", 
12:20:46          "E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/libi/libiscsi/libiscsi7_1.17.0-1.1_amd64.deb  503  Service Unavailable [IP: 34.212.136.213 80]", 
12:20:46          "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"
12:20:46      ], ```

**Comment by jwk404** [comment] 2019-12-02 20:52
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/2192/
```
02:26:40          "'Error reading https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&exact=on&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367: Internal Server Error'"
02:26:40      ]
02:26:40  }
02:26:40  	to retry, use: --limit @/var/tmp/jenkins/workspace/devops-gate/master/appliance-build-stage1/master/post-push/appliance-build/bootstrap/playbook.retry
02:26:40  
02:26:40  PLAY RECAP *********************************************************************
02:26:40  localhost                  : ok=4    changed=3    unreachable=0    failed=1   
```

**Comment by mdebb** [comment] 2019-12-03 16:36
The Undetermined Error [IP: 91.189.88.149 80] errors are caused by a known apt bug when the web server closes the tcp connection after the last transferred file (servicing the last allowed request in a keepalive session).
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1801338

**Comment by pzakha** [comment] 2019-12-03 22:54
Thanks a lot for the info @mdebb! I'll dig into it

**Comment by mdebb** [comment] 2019-12-05 09:22
You are welcome. I just posted this apt configuration workaround launchpad:
    Acquire {
       http::Pipeline-Depth "0";
   };

**Comment by pzakha** [comment] 2020-03-02 15:50
@mdebb Not sure how you found this, but that did solve the Undetermined Error issue in our build. Many thanks.

**Comment by pzakha** [comment] 2020-03-02 15:51
Closing this as we are not using external archives anymore and the Undetermined Error issue for internal builds was fixed.

**Closed by pzakha** 2020-03-02 15:51 UTC

**Comment by An-prog-hub** [comment] 2021-08-22 11:09
while checking for the npm version I am getting this error.

```
➜  ~ npm -v
/mnt/c/Program Files/nodejs//npm: line 3: $'\r': command not found
/mnt/c/Program Files/nodejs//npm: line 5: $'\r': command not found
/mnt/c/Program Files/nodejs//npm: line 6: syntax error near unexpected token `$'in\r''
'mnt/c/Program Files/nodejs//npm: line 6: `case `uname` in
➜  ~ sudo apt install nodejs npm
[sudo] password for ankush:
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version (10.19.0~dfsg-3ubuntu1).
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu build-essential cpp cpp-9 dpkg-dev fakeroot g++ g++-9 gcc gcc-9
  gcc-9-base gyp javascript-common libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan5
  libatomic1 libauthen-sasl-perl libbinutils libc-dev-bin libc6-dev libcc1-0 libcrypt-dev libctf-nobfd0 libctf0
  libdata-dump-perl libdpkg-perl libencode-locale-perl libfakeroot libfile-basedir-perl libfile-desktopentry-perl
  libfile-fcntllock-perl libfile-listing-perl libfile-mimeinfo-perl libfont-afm-perl libgcc-9-dev libgomp1
  libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl
  libhttp-daemon-perl libhttp-date-perl libhttp-message-perl libhttp-negotiate-perl libio-html-perl
  libio-socket-ssl-perl libio-stringy-perl libipc-system-simple-perl libisl22 libitm1 libjs-inherits
  libjs-is-typedarray libjs-psl libjs-typedarray-to-buffer liblsan0 liblwp-mediatypes-perl liblwp-protocol-https-perl
  libmailtools-perl libmpc3 libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl libnode-dev
  libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libquadmath0 libssl-dev libstdc++-9-dev
  libtie-ixhash-perl libtimedate-perl libtry-tiny-perl libtsan0 libubsan1 liburi-perl libuv1-dev libwww-perl
  libwww-robotrules-perl libx11-protocol-perl libxcursor1 libxml-parser-perl libxml-twig-perl libxml-xpathengine-perl
  linux-libc-dev make manpages-dev node-abbrev node-ajv node-ansi node-ansi-align node-ansi-regex node-ansi-styles
  node-ansistyles node-aproba node-archy node-are-we-there-yet node-asap node-asn1 node-assert-plus node-asynckit
  node-aws-sign2 node-aws4 node-balanced-match node-bcrypt-pbkdf node-bl node-bluebird node-boxen node-brace-expansion
  node-builtin-modules node-builtins node-cacache node-call-limit node-camelcase node-caseless node-chalk node-chownr
  node-ci-info node-cli-boxes node-cliui node-clone node-co node-color-convert node-color-name node-colors
  node-columnify node-combined-stream node-concat-map node-concat-stream node-config-chain node-configstore
  node-console-control-strings node-copy-concurrently node-core-util-is node-cross-spawn node-crypto-random-string
  node-cyclist node-dashdash node-debug node-decamelize node-decompress-response node-deep-extend node-defaults
  node-define-properties node-delayed-stream node-delegates node-detect-indent node-detect-newline node-dot-prop
  node-duplexer3 node-duplexify node-ecc-jsbn node-editor node-encoding node-end-of-stream node-err-code node-errno
  node-es6-promise node-escape-string-regexp node-execa node-extend node-extsprintf node-fast-deep-equal node-find-up
  node-flush-write-stream node-forever-agent node-form-data node-from2 node-fs-vacuum node-fs-write-stream-atomic
  node-fs.realpath node-function-bind node-gauge node-genfun node-get-caller-file node-get-stream node-getpass
  node-glob node-got node-graceful-fs node-gyp node-har-schema node-har-validator node-has-flag
  node-has-symbol-support-x node-has-to-string-tag-x node-has-unicode node-hosted-git-info node-http-signature
  node-iconv-lite node-iferr node-import-lazy node-imurmurhash node-inflight node-inherits node-ini node-invert-kv
  node-ip node-ip-regex node-is-npm node-is-obj node-is-object node-is-path-inside node-is-plain-obj
  node-is-retry-allowed node-is-stream node-is-typedarray node-isarray node-isexe node-isstream node-isurl node-jsbn
  node-json-parse-better-errors node-json-schema node-json-schema-traverse node-json-stable-stringify
  node-json-stringify-safe node-jsonify node-jsonparse node-jsonstream node-jsprim node-latest-version
  node-lazy-property node-lcid node-libnpx node-locate-path node-lockfile node-lodash node-lodash-packages
  node-lowercase-keys node-lru-cache node-make-dir node-mem node-mime node-mime-types node-mimic-fn
  node-mimic-response node-minimatch node-minimist node-mississippi node-mkdirp node-move-concurrently node-ms
  node-mute-stream node-nopt node-normalize-package-data node-npm-bundled node-npm-package-arg node-npm-run-path
  node-npmlog node-number-is-nan node-oauth-sign node-object-assign node-once node-opener node-os-locale
  node-os-tmpdir node-osenv node-p-cancelable node-p-finally node-p-is-promise node-p-limit node-p-locate
  node-p-timeout node-package-json node-parallel-transform node-path-exists node-path-is-absolute node-path-is-inside
  node-performance-now node-pify node-prepend-http node-process-nextick-args node-promise-inflight node-promise-retry
  node-promzard node-proto-list node-prr node-pseudomap node-psl node-pump node-pumpify node-punycode node-qs node-qw
  node-rc node-read node-read-package-json node-readable-stream node-registry-auth-token node-registry-url
  node-request node-require-directory node-require-main-filename node-resolve node-resolve-from node-retry node-rimraf
  node-run-queue node-safe-buffer node-semver node-semver-diff node-set-blocking node-sha node-shebang-command
  node-shebang-regex node-signal-exit node-slash node-slide node-sorted-object node-spdx-correct node-spdx-exceptions
  node-spdx-expression-parse node-spdx-license-ids node-sshpk node-ssri node-stream-each node-stream-iterate
  node-stream-shift node-strict-uri-encode node-string-decoder node-string-width node-strip-ansi node-strip-eof
  node-strip-json-comments node-supports-color node-tar node-term-size node-text-table node-through node-through2
  node-timed-out node-tough-cookie node-tunnel-agent node-tweetnacl node-typedarray node-typedarray-to-buffer
  node-uid-number node-unique-filename node-unique-string node-unpipe node-uri-js node-url-parse-lax
  node-url-to-options node-util-deprecate node-uuid node-validate-npm-package-license node-validate-npm-package-name
  node-verror node-wcwidth.js node-which node-which-module node-wide-align node-widest-line node-wrap-ansi node-wrappy
  node-write-file-atomic node-xdg-basedir node-xtend node-y18n node-yallist node-yargs node-yargs-parser
  perl-openssl-defaults python-pkg-resources python2 python2-minimal python2.7 python2.7-minimal x11-xserver-utils
  xdg-utils
Suggested packages:
  binutils-doc cpp-doc gcc-9-locales debian-keyring g++-multilib g++-9-multilib gcc-9-doc gcc-multilib autoconf
  automake libtool flex bison gdb gcc-doc gcc-9-multilib apache2 | lighttpd | httpd libdigest-hmac-perl libgssapi-perl
  glibc-doc bzr libcrypt-ssleay-perl libssl-doc libstdc++-9-doc libauthen-ntlm-perl libunicode-map8-perl
  libunicode-string-perl xml-twig-tools make-doc python-setuptools python2-doc python-tk python2.7-doc binfmt-support
  nickle cairo-5c xorg-docs-core
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu build-essential cpp cpp-9 dpkg-dev fakeroot g++ g++-9 gcc gcc-9
  gcc-9-base gyp javascript-common libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan5
  libatomic1 libauthen-sasl-perl libbinutils libc-dev-bin libc6-dev libcc1-0 libcrypt-dev libctf-nobfd0 libctf0
  libdata-dump-perl libdpkg-perl libencode-locale-perl libfakeroot libfile-basedir-perl libfile-desktopentry-perl
  libfile-fcntllock-perl libfile-listing-perl libfile-mimeinfo-perl libfont-afm-perl libgcc-9-dev libgomp1
  libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl
  libhttp-daemon-perl libhttp-date-perl libhttp-message-perl libhttp-negotiate-perl libio-html-perl
  libio-socket-ssl-perl libio-stringy-perl libipc-system-simple-perl libisl22 libitm1 libjs-inherits
  libjs-is-typedarray libjs-psl libjs-typedarray-to-buffer liblsan0 liblwp-mediatypes-perl liblwp-protocol-https-perl
  libmailtools-perl libmpc3 libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl libnode-dev
  libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libquadmath0 libssl-dev libstdc++-9-dev
  libtie-ixhash-perl libtimedate-perl libtry-tiny-perl libtsan0 libubsan1 liburi-perl libuv1-dev libwww-perl
  libwww-robotrules-perl libx11-protocol-perl libxcursor1 libxml-parser-perl libxml-twig-perl libxml-xpathengine-perl
  linux-libc-dev make manpages-dev node-abbrev node-ajv node-ansi node-ansi-align node-ansi-regex node-ansi-styles
  node-ansistyles node-aproba node-archy node-are-we-there-yet node-asap node-asn1 node-assert-plus node-asynckit
  node-aws-sign2 node-aws4 node-balanced-match node-bcrypt-pbkdf node-bl node-bluebird node-boxen node-brace-expansion
  node-builtin-modules node-builtins node-cacache node-call-limit node-camelcase node-caseless node-chalk node-chownr
  node-ci-info node-cli-boxes node-cliui node-clone node-co node-color-convert node-color-name node-colors
  node-columnify node-combined-stream node-concat-map node-concat-stream node-config-chain node-configstore
  node-console-control-strings node-copy-concurrently node-core-util-is node-cross-spawn node-crypto-random-string
  node-cyclist node-dashdash node-debug node-decamelize node-decompress-response node-deep-extend node-defaults
  node-define-properties node-delayed-stream node-delegates node-detect-indent node-detect-newline node-dot-prop
  node-duplexer3 node-duplexify node-ecc-jsbn node-editor node-encoding node-end-of-stream node-err-code node-errno
  node-es6-promise node-escape-string-regexp node-execa node-extend node-extsprintf node-fast-deep-equal node-find-up
  node-flush-write-stream node-forever-agent node-form-data node-from2 node-fs-vacuum node-fs-write-stream-atomic
  node-fs.realpath node-function-bind node-gauge node-genfun node-get-caller-file node-get-stream node-getpass
  node-glob node-got node-graceful-fs node-gyp node-har-schema node-har-validator node-has-flag
  node-has-symbol-support-x node-has-to-string-tag-x node-has-unicode node-hosted-git-info node-http-signature
  node-iconv-lite node-iferr node-import-lazy node-imurmurhash node-inflight node-inherits node-ini node-invert-kv
  node-ip node-ip-regex node-is-npm node-is-obj node-is-object node-is-path-inside node-is-plain-obj
  node-is-retry-allowed node-is-stream node-is-typedarray node-isarray node-isexe node-isstream node-isurl node-jsbn
  node-json-parse-better-errors node-json-schema node-json-schema-traverse node-json-stable-stringify
  node-json-stringify-safe node-jsonify node-jsonparse node-jsonstream node-jsprim node-latest-version
  node-lazy-property node-lcid node-libnpx node-locate-path node-lockfile node-lodash node-lodash-packages
  node-lowercase-keys node-lru-cache node-make-dir node-mem node-mime node-mime-types node-mimic-fn
  node-mimic-response node-minimatch node-minimist node-mississippi node-mkdirp node-move-concurrently node-ms
  node-mute-stream node-nopt node-normalize-package-data node-npm-bundled node-npm-package-arg node-npm-run-path
  node-npmlog node-number-is-nan node-oauth-sign node-object-assign node-once node-opener node-os-locale
  node-os-tmpdir node-osenv node-p-cancelable node-p-finally node-p-is-promise node-p-limit node-p-locate
  node-p-timeout node-package-json node-parallel-transform node-path-exists node-path-is-absolute node-path-is-inside
  node-performance-now node-pify node-prepend-http node-process-nextick-args node-promise-inflight node-promise-retry
  node-promzard node-proto-list node-prr node-pseudomap node-psl node-pump node-pumpify node-punycode node-qs node-qw
  node-rc node-read node-read-package-json node-readable-stream node-registry-auth-token node-registry-url
  node-request node-require-directory node-require-main-filename node-resolve node-resolve-from node-retry node-rimraf
  node-run-queue node-safe-buffer node-semver node-semver-diff node-set-blocking node-sha node-shebang-command
  node-shebang-regex node-signal-exit node-slash node-slide node-sorted-object node-spdx-correct node-spdx-exceptions
  node-spdx-expression-parse node-spdx-license-ids node-sshpk node-ssri node-stream-each node-stream-iterate
  node-stream-shift node-strict-uri-encode node-string-decoder node-string-width node-strip-ansi node-strip-eof
  node-strip-json-comments node-supports-color node-tar node-term-size node-text-table node-through node-through2
  node-timed-out node-tough-cookie node-tunnel-agent node-tweetnacl node-typedarray node-typedarray-to-buffer
  node-uid-number node-unique-filename node-unique-string node-unpipe node-uri-js node-url-parse-lax
  node-url-to-options node-util-deprecate node-uuid node-validate-npm-package-license node-validate-npm-package-name
  node-verror node-wcwidth.js node-which node-which-module node-wide-align node-widest-line node-wrap-ansi node-wrappy
  node-write-file-atomic node-xdg-basedir node-xtend node-y18n node-yallist node-yargs node-yargs-parser npm
  perl-openssl-defaults python-pkg-resources python2 python2-minimal python2.7 python2.7-minimal x11-xserver-utils
  xdg-utils
0 upgraded, 378 newly installed, 0 to remove and 0 not upgraded.
Need to get 3726 kB/52.3 MB of archives.
After this operation, 237 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Ign:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-libc-dev amd64 5.4.0-65.73
Ign:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libcc1-0 amd64 10.2.0-5ubuntu1~20.04
Ign:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgomp1 amd64 10.2.0-5ubuntu1~20.04
Ign:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libitm1 amd64 10.2.0-5ubuntu1~20.04
Ign:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libatomic1 amd64 10.2.0-5ubuntu1~20.04
Ign:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 liblsan0 amd64 10.2.0-5ubuntu1~20.04
Ign:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libtsan0 amd64 10.2.0-5ubuntu1~20.04
Ign:8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libubsan1 amd64 10.2.0-5ubuntu1~20.04
Ign:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libquadmath0 amd64 10.2.0-5ubuntu1~20.04
Ign:10 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libssl-dev amd64 1.1.1f-1ubuntu2.2
Ign:11 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libuv1-dev amd64 1.34.2-1ubuntu1.1
Err:1 http://security.ubuntu.com/ubuntu focal-updates/main amd64 linux-libc-dev amd64 5.4.0-65.73
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:2 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libcc1-0 amd64 10.2.0-5ubuntu1~20.04
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:3 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libgomp1 amd64 10.2.0-5ubuntu1~20.04
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:4 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libitm1 amd64 10.2.0-5ubuntu1~20.04
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:5 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libatomic1 amd64 10.2.0-5ubuntu1~20.04
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:6 http://security.ubuntu.com/ubuntu focal-updates/main amd64 liblsan0 amd64 10.2.0-5ubuntu1~20.04
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:7 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libtsan0 amd64 10.2.0-5ubuntu1~20.04
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:8 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libubsan1 amd64 10.2.0-5ubuntu1~20.04
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:9 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libquadmath0 amd64 10.2.0-5ubuntu1~20.04
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:10 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libssl-dev amd64 1.1.1f-1ubuntu2.2
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Err:11 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libuv1-dev amd64 1.34.2-1ubuntu1.1
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.4.0-65.73_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10/libcc1-0_10.2.0-5ubuntu1~20.04_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10/libgomp1_10.2.0-5ubuntu1~20.04_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10/libitm1_10.2.0-5ubuntu1~20.04_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10/libatomic1_10.2.0-5ubuntu1~20.04_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10/liblsan0_10.2.0-5ubuntu1~20.04_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10/libtsan0_10.2.0-5ubuntu1~20.04_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10/libubsan1_10.2.0-5ubuntu1~20.04_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-10/libquadmath0_10.2.0-5ubuntu1~20.04_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.2_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libu/libuv1/libuv1-dev_1.34.2-1ubuntu1.1_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::23 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
