### ISSUE TITLE
Timeout "aws s3 sync --delete" in internal-dev-azure

### ISSUE THREAD

**Issue by shartse** [delphix/appliance-build#221] opened 2019-01-30 19:00 UTC
We can see the `internal-dev-azure` pipeline step times out and is cancelled here: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/471/flowGraphTable/

The tasks running before the hang and cancellation are here:
```
12:22:27 + mv ../SHA256SUMS SHA256SUMS
[Pipeline] sh
12:22:28 + aws s3 sync --delete --only-show-errors . s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/master/post-push/471/internal-dev-azure/
Calling Pipeline was cancelled
23:06:27 Calling Pipeline was cancelled
Sending interrupt signal to process
23:06:28 Sending interrupt signal to process
23:06:34 /var/tmp/jenkins/workspace/devops-gate/master/appliance-build-stage1/master/post-push/appliance-build/live-build/build/artifacts@tmp/durable-0b88a1ce/script.sh: line 1: 21495 Terminated              aws s3 sync --delete --only-show-errors . s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/master/post-push/471/internal-dev-azure/
23:06:34 script returned exit code 143
```

**Comment by prakashsurya** [comment] 2019-01-30 23:21
I think this is a duplicate of #183

**Closed** 2019-02-08 23:42 UTC
