### ISSUE TITLE
Failure to export rpool in 90-raw-disk-image.binary

### ISSUE THREAD

**Issue by jwk404** [delphix/appliance-build#589] opened 2021-08-10 19:50 UTC
This bug is almost the same as https://github.com/delphix/appliance-build/issues/431

** Expected Behavior**
rpool should be exported after the root fs is unmounted.

** Actual Behavior**
Describe what actually happened.

```
00:57:03  + for dir in /dev /proc /sys
00:57:03  + for attempt in {1..5}
00:57:03  + umount -R /mnt/delphix.Y6SI2Vj/sys
00:57:03  + break
00:57:03  + umount /mnt/delphix.Y6SI2Vj/var/log
00:57:03  + umount /mnt/delphix.Y6SI2Vj/var/delphix
00:57:03  + umount /mnt/delphix.Y6SI2Vj/export/home
00:57:03  + umount /var/crash
00:57:03  + zfs umount rpool/ROOT/delphix.Y6SI2Vj/root
00:57:03  + zpool export rpool
00:57:03  cannot export 'rpool': pool is busy
00:57:03  E: config/hooks/90-raw-disk-image.binary failed (exit non-zero). You should check for errors.
```

http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/post-push/118947/console
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/post-push/118915/consoleFull

**Comment by pzakha** [comment] 2021-08-13 18:55
Note that this only affects the focal branch.
I'm closing this as duplicate of the JIRA bug: https://jira.delphix.com/browse/TOOL-11972

**Closed by pzakha** 2021-08-13 18:55 UTC
