### ISSUE TITLE
intermittent failures due to Docker crashing

### ISSUE THREAD

**Issue by sdimitro** [delphix/appliance-build#240] opened 2019-03-01 20:13 UTC
We recently had a failure with the following out:
```
23:06:11 TASK [appliance-build.bootstrap : shell] ***************************************
23:06:11 task path: /var/tmp/jenkins/workspace/devops-gate/master/appliance-build-stage1/master/post-push/appliance-build/bootstrap/roles/appliance-build.bootstrap/tasks/main.yml:45
....
00:01:34 fatal: [localhost]: FAILED! => {
00:01:34     "changed": true, 
00:01:34     "cmd": "docker build --network host --tag \"appliance-build:latest\" \
......
00:01:34     }, 
00:01:34     "msg": "non-zero return code", 
00:01:34     "rc": 100, 
00:01:34     "start": "2019-02-27 07:06:10.393680", 
00:01:34     "stderr": "free(): invalid pointer\nSIGABRT: abort\nPC=0x7faddf2e3e97 m=0 sigcode=18446744073709551610\nsignal arrived during cgo execution\n\ngoroutine 1 [syscall, locked to thread]:\nruntime.cgocall(0x4afd50, 0xc420049cc0, 0xc420049ce8)\n\t/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420049c90 sp=0xc420049c50\ngithub.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x249eda0)\n\tgithub.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420049cc0 sp=0xc420049c90\ngithub.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x249eda0)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420049cf8 sp=0xc420049cc0\ngithub.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc4200100d0)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420049da0 sp=0xc420049cf8\ngithub.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420049e88, 0x410022, 0xc420060220)\n\t<autogenerated>:4 +0x46 fp=0xc420049de0 sp=0xc420049da0\ngithub.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc420080008, 0x0, 0x10)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420049e68 sp=0xc420049de0\ngithub.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffd62e5cd53, 0x4, 0x7560a0, 0xc420080000, 0x7560e0, 0xc420080008, 0x40e398, 0x4d35c0)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420049ed8 sp=0xc420049e68\ngithub.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420049f58 sp=0xc420049ed8\nmain.main()\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420049f88 sp=0xc420049f58\nruntime.main()\n\t/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420049fe0 sp=0xc420049f88\nruntime.goexit()\n\t/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420049fe8 sp=0xc420049fe0\n\ngoroutine 17 [syscall, locked to thread]:\nruntime.goexit()\n\t/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1\n\nrax    0x0\nrbx    0x7ffd62e5ab50\nrcx    0x7faddf2e3e97\nrdx    0x0\nrdi    0x2\nrsi    0x7ffd62e5a8e0\nrbp    0x7ffd62e5ac50\nrsp    0x7ffd62e5a8e0\nr8     0x0\nr9     0x7ffd62e5a8e0\nr10    0x8\nr11    0x246\nr12    0x7ffd62e5ab50\nr13    0x1000\nr14    0x0\nr15    0x30\nrip    0x7faddf2e3e97\nrflags 0x246\ncs     0x33\nfs     0x0\ngs     0x0\nThe command '/bin/bash -c apt-get update &&   apt-get install -y software-properties-common &&   apt-add-repository -y ppa:ansible/ansible &&   apt-get update &&   apt-get install -y       ansible       aptly       awscli       bc       coreutils       equivs       gdisk       git       java-package       jq       kpartx       libxt6       livecd-rootfs       make       man       openjdk-8-jre-headless       pigz       rename       shellcheck       vim       zfsutils-linux &&   rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100", 
00:01:34     "stderr_lines": [
00:01:34         "free(): invalid pointer", 
00:01:34         "SIGABRT: abort", 
00:01:34         "PC=0x7faddf2e3e97 m=0 sigcode=18446744073709551610", 
00:01:34         "signal arrived during cgo execution", 
00:01:34         "", 
00:01:34         "goroutine 1 [syscall, locked to thread]:", 
00:01:34         "runtime.cgocall(0x4afd50, 0xc420049cc0, 0xc420049ce8)", 
00:01:34         "\t/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420049c90 sp=0xc420049c50", 
00:01:34         "github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x249eda0)", 
00:01:34         "\tgithub.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420049cc0 sp=0xc420049c90", 
00:01:34         "github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x249eda0)", 
00:01:34         "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420049cf8 sp=0xc420049cc0", 
00:01:34         "github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc4200100d0)", 
00:01:34         "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420049da0 sp=0xc420049cf8", 
00:01:34         "github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420049e88, 0x410022, 0xc420060220)", 
00:01:34         "\t<autogenerated>:4 +0x46 fp=0xc420049de0 sp=0xc420049da0", 
00:01:34         "github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc420080008, 0x0, 0x10)", 
00:01:34         "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420049e68 sp=0xc420049de0", 
00:01:34         "github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffd62e5cd53, 0x4, 0x7560a0, 0xc420080000, 0x7560e0, 0xc420080008, 0x40e398, 0x4d35c0)", 
00:01:34         "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420049ed8 sp=0xc420049e68", 
00:01:34         "github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)", 
00:01:34         "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420049f58 sp=0xc420049ed8", 
00:01:34         "main.main()", 
00:01:34         "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420049f88 sp=0xc420049f58", 
00:01:34         "runtime.main()", 
00:01:34         "\t/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420049fe0 sp=0xc420049f88", 
00:01:34         "runtime.goexit()", 
00:01:34         "\t/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420049fe8 sp=0xc420049fe0", 
00:01:34         "", 
00:01:34         "goroutine 17 [syscall, locked to thread]:", 
00:01:34         "runtime.goexit()", 
00:01:34         "\t/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1", 
00:01:34         "", 
00:01:34         "rax    0x0", 
00:01:34         "rbx    0x7ffd62e5ab50", 
00:01:34         "rcx    0x7faddf2e3e97", 
00:01:34         "rdx    0x0", 
00:01:34         "rdi    0x2", 
00:01:34         "rsi    0x7ffd62e5a8e0", 
00:01:34         "rbp    0x7ffd62e5ac50", 
00:01:34         "rsp    0x7ffd62e5a8e0", 
00:01:34         "r8     0x0", 
00:01:34         "r9     0x7ffd62e5a8e0", 
00:01:34         "r10    0x8", 
00:01:34         "r11    0x246", 
00:01:34         "r12    0x7ffd62e5ab50", 
00:01:34         "r13    0x1000", 
00:01:34         "r14    0x0", 
00:01:34         "r15    0x30", 
00:01:34         "rip    0x7faddf2e3e97", 
00:01:34         "rflags 0x246", 
00:01:34         "cs     0x33", 
00:01:34         "fs     0x0", 
00:01:34         "gs     0x0", 
00:01:34         "The command '/bin/bash -c apt-get update &&   apt-get install -y software-properties-common &&   apt-add-repository -y ppa:ansible/ansible &&   apt-get update &&   apt-get install -y       ansible       aptly       awscli       bc       coreutils       equivs       gdisk       git       java-package       jq       kpartx       libxt6       livecd-rootfs       make       man       openjdk-8-jre-headless       pigz       rename       shellcheck       vim       zfsutils-linux &&   rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100"
00:01:34     ]
```
reference: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/1692/consoleFull

This seems to be a known Docker issue: https://github.com/moby/moby/issues/37916

Reading the comments it seems like there is a fix for it but haven't made it to the mainline yet.

**Comment by jgallag88** [comment] 2019-03-01 21:00
While we do hit this error, it doesn't seem to be causing any problems, since it turns up in the output of successful jobs as well. I think the cause of the failure in this particular run was
```
00:01:34         "Get:353 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 zfsutils-linux amd64 0.7.5-1ubuntu16.4 [341 kB]", 
00:01:34         "Get:354 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 zfs-zed amd64 0.7.5-1ubuntu16.4 [57.7 kB]", 
00:01:34         "Fetched 187 MB in 52min 44s (59.2 kB/s)", 
00:01:34         "\u001b[91mE: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/parted/parted_3.2-20ubuntu0.1_amd64.deb  Undetermined Error [IP: 91.189.88.149 80]", 
00:01:34         "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?", 
00:01:34         "\u001b[0m"
```

**Comment by sdimitro** [comment] 2019-03-01 21:42
Yeah you are right, it seems like maybe a case of https://github.com/delphix/appliance-build/issues/146 ?

**Comment by jgallag88** [comment] 2019-03-01 21:50
Yeah, looks like it

**Comment by prakashsurya** [comment] 2019-07-03 22:06
This appears to be a duplicate of #146, so I'm closing this.

**Closed by prakashsurya** 2019-07-03 22:06 UTC
