### ISSUE TITLE
unmet dependencies due to missing delphix-kernel causes build failures

### ISSUE THREAD

**Issue by prakashsurya** [delphix/appliance-build#163] opened 2018-12-03 17:52 UTC
```
09:22:51 The following packages have unmet dependencies:
09:22:51  ****-platform : Depends: ****-kernel
09:22:51 E: Unable to correct problems, you have held broken packages.
```
see here: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/post-push/266/console

@pzakha can you comment on the root cause for this, and the workaround to alleviate the issue when it occurs?

**Comment by pzakha** [comment] 2018-12-03 20:48
**BUG DESCRIPTION**
I think the root cause for this is that the `delphix-kernel-$KVERS` package couldn't be installed because the kernel version it depends on was not available in the ubuntu archive as the latter was updated with a newer kernel version.
We do not currently install `delphix-kernel-$KVERS` explicitly, but instead get it as a dependency of `delphix-platform`, which depends on virtual package `delphix-kernel` provided by `delphix-kernel-$KVERS`.
I believe `apt` complained about `delphix-platform` having unmet dependency `delphix-kernel` instead of `delphix-kernel-$KVERS` having unmet dependency `linux-image-$KVERS` because it didn't even attempt installing `delphix-kernel-$KVERS`. If `delphix-platform` depended on `delphix-kernel-$KVERS` explicitly, it would have probably displayed a different error message.

**WORKAROUND**
To work around that, we need to rebuild `delphix-kernel` against the newer kernel (note that `delphix-kernel` is provided by `linux-pkg` so we rebuild the latter). It is also advisable to trigger a rebuild of `zfs` since it is also built against a specific kernel version.
Steps:
1. Rebuild `linux-pkg`: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/post-push/
2. Rebuilt `zfs`: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-package-build/job/master/job/post-push/

**Comment by pzakha** [comment] 2018-12-20 15:56
We had a few instances of this last night because the kernel was updated and ZFS packages didn't get rebuilt for some time.
This issue should be fixed by project https://jira.delphix.com/browse/LB-117, in particular by subtask https://jira.delphix.com/browse/LB-142.

**Comment by pzakha** [comment] 2021-08-13 18:15
This category of issues has been eliminated since the linux-pkg rework and the build of our in-house kernels.

**Closed by pzakha** 2021-08-13 18:15 UTC
